#!/bin/bash

cp -v beaches-78a.jpg ./convert
cp -v beautiful_young_forest-wallpaper-1920x1200.jpg ./convert
cp -v breathtaking_nature-wallpaper-1920x1200.jpg ./convert
cp -v clouds-39a.jpg ./convert
cp -v delicate_waves-wallpaper-1920x1200.jpg ./convert
cp -v golden_morning-wallpaper-1920x1200.jpg ./convert
cp -v grove_2-wallpaper-1920x1200.jpg ./convert
cp -v hawaii_11.jpg ./convert
cp -v hawaii_12.jpg ./convert
cp -v hawaii_13.jpg ./convert
cp -v hawaii_14.jpg ./convert
cp -v hawaii_15.jpg ./convert
cp -v hawaii_16.jpg ./convert
cp -v hawaii_1.jpg ./convert
cp -v hawaii_2.jpg ./convert
cp -v hawaii_4.jpg ./convert
cp -v hawaii_5.jpg ./convert
cp -v hawaii_7.jpg ./convert
cp -v hawaii_8.jpg ./convert
cp -v hawaii_9.jpg ./convert
cp -v iceland_lake_2-wallpaper-1920x1200.jpg ./convert
cp -v iceland_landscape-wallpaper-1920x1200.jpg ./convert
cp -v landscapes-202a.jpg ./convert
cp -v landscapes-205v.jpg ./convert
cp -v landscapes-207a.jpg ./convert
cp -v landscapes-211a.jpg ./convert
cp -v landscapes-214a.jpg ./convert
cp -v landscapes-215a.jpg ./convert
cp -v landscapes-224a.jpg ./convert
cp -v landscapes-226a.jpg ./convert
cp -v landscapes-229v.jpg ./convert
cp -v landscapes-241a.jpg ./convert
cp -v landscapes-246a.jpg ./convert
cp -v landscapes-250v.jpg ./convert
cp -v misty_morning_2-wallpaper-1920x1200.jpg ./convert
cp -v moss_on_the_rocks-wallpaper-1920x1200.jpg ./convert
cp -v mountain-226a.jpg ./convert
cp -v mountain-227a.jpg ./convert
cp -v mountain-232a.jpg ./convert
cp -v mountain-236a.jpg ./convert
cp -v mountain_river_5-wallpaper-1920x1200.jpg ./convert
cp -v old_stones_barrage-wallpaper-1920x1200.jpg ./convert
cp -v purpleworld11.jpg ./convert
cp -v purpleworld13.jpg ./convert
cp -v purpleworld15.jpg ./convert
cp -v purpleworld17.jpg ./convert
cp -v purpleworld19.jpg ./convert
cp -v purpleworld1.jpg ./convert
cp -v purpleworld3.jpg ./convert
cp -v purpleworld5.jpg ./convert
cp -v purpleworld7.jpg ./convert
cp -v purpleworld9.jpg ./convert
cp -v rainbow_sunset-wallpaper-1920x1200.jpg ./convert
cp -v reflexos_2-wallpaper-1920x1200.jpg ./convert
cp -v road_among_trees-wallpaper-1920x1200.jpg ./convert
cp -v saltlakesdeadseas10_ca.jpg ./convert
cp -v saltlakesdeadseas12_sa.jpg ./convert
cp -v saltlakesdeadseas13_ca.jpg ./convert
cp -v saltlakesdeadseas14_ds.jpg ./convert
cp -v saltlakesdeadseas15_af.jpg ./convert
cp -v saltlakesdeadseas1_sa.jpg ./convert
cp -v saltlakesdeadseas2_ds.jpg ./convert
cp -v saltlakesdeadseas3_ca.jpg ./convert
cp -v saltlakesdeadseas4_ut.jpg ./convert
cp -v saltlakesdeadseas6_ca.jpg ./convert
cp -v saltlakesdeadseas7_sa.jpg ./convert
cp -v saltlakesdeadseas8_ds.jpg ./convert
cp -v saltlakesdeadseas9_af.jpg ./convert
cp -v sierra_nevada_red_trees-wallpaper-1920x1200.jpg ./convert
cp -v snowy_mountain_peaks_5-wallpaper-1920x1200.jpg ./convert
cp -v snowy_mountain_peak_summer-wallpaper-1920x1200.jpg ./convert
cp -v sunrise_over_acatenango_volcano_guatemala-wallpaper-1920x1080.jpg ./convert
cp -v sunset_150-wallpaper-1920x1200.jpg ./convert
cp -v sunset-175a.jpg ./convert
cp -v sunset-177a.jpg ./convert
cp -v sunset-185a.jpg ./convert
cp -v sunset_over_rust-wallpaper-1920x1200.jpg ./convert
cp -v under_the_tree_2-wallpaper-1920x1200.jpg ./convert
cp -v waterfalls-10v.jpg ./convert
cp -v waterfalls-20a.jpg ./convert
cp -v waterfalls-21a.jpg ./convert
cp -v widest_waterfall_in_the_world-wallpaper-1920x1080.jpg ./convert
